# Python, päev1

Täna õpime Pythoni baas asju kasutama.

## *Hello, World*

In [2]:
print("Hello, World!")

Hello, World!

In [4]:
"Hello, World!"

'Hello, World!'

# Andmetüübid

In [7]:
PI = 3,14159 # floart ehk ujukoma arv
aasta = 2026 # int ehk täisarv
sun_rises_from_east = True # bool ehk tõeväärtus

In [15]:
year = [2020, 2021, 2022, 2024] # list ehk nimekiri , järjestatud ja muudetav kogum elemente
person = {
    "name": "Alice",
    "age": 30,
    "city": "New York"
} # dict ehk sõnastik, võtme-väärtuse paaride kogum, muutuv ja järjestamata

fruits = {"apple", "banana", "cherry"} # set ehk hulk, järjestatud ja muutumatu kogum elemente
tuple_example = (1, 2, 3) # tuple ehk ennik, järjestatud ja muutumatu kogum element

# Funktsioonid

In [47]:
def greet (name: str, time_of_day: str = "day") -> None:
    print (f"Good {time_of_day}, {name}!")

In [26]:
print ("Hello from a function!")
print ("And some more things going on in here...")

Hello from a function!
And some more things going on in here...

In [32]:
number = 42
f"Number is {number}"

'Number is 42'

In [56]:
greet("Toomas")
greet("Toomas", "evening")
greet(name="Toomas", time_of_day="evening")

Good day, Toomas!
Good evening, Toomas!
Good evening, Toomas!

In [169]:
def add(a: int, b: int) -> int:
    return a + b

In [59]:
add (1, 2)

3

## if/else

In [170]:
def make_sense_of_this_year(year: int):
    if year < 0:
        print("B.C")
        if year < -10000:
            print("Stone age...")
    elif year == 0:
        print("Happy Birthday, Jesus!")

    elif year == 1978:
        print("Happy Birthday, Mati!")
    else:
        print("A.D.")

make_sense_of_this_year(year=-900000)

B.C
Stone age...

In [171]:
def print_year(year: int):
    if year < 0:
        print(f"{abs(year)} B.C")
    else:
        print(f"{year} A.D.")

print_year(-90)
print_year(2025)

90 B.C
2025 A.D.

In [82]:
import datetime

datetime.date.today()

datetime.date(2026, 4, 9)

## For Loop

In [173]:
years = [2021, 2022, 2023,  2024, 2025]

for year in years:
    print(f"Happy start of {year}")

Happy start of 2021
Happy start of 2022
Happy start of 2023
Happy start of 2024
Happy start of 2025

In [174]:
years = [2021, 2022, 2023, 2024, 2025]

for year in years[:3]:
    print(f"Happy start of {year}")

Happy start of 2021
Happy start of 2022
Happy start of 2023

In [93]:
years [3:]

[2024, 2025]

In [2]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!

## Pandas

In [95]:
!pip3 install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.4.4-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jaana\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\jaana\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 3.5 MB/s eta 0:00:03
   ---- ----------------------------------- 1.0/9.9 MB 3.5 MB/s eta 0:00:03
   ------- -------------------------------- 1.8/9.9 MB 3.4 MB/s eta 0:00:03
   ---------- ----------------------------- 2.6/9.9 MB 3.4 MB/s eta 0:00:03
   ------------ --------------------------- 3.1/9.9 MB 3.4 MB/s eta 0:00:02
   --------------- ------------------------ 3.9/9.9 MB 3.4 MB/s eta 0:00:02
   ------------------- -------------------- 4.7/9.9 MB 3.4 MB/s eta 0:00:02
   --------------------- ------------------ 5.2/9.9 MB 3.4 MB/s eta 0:00:02
   ------------------------ --------------- 6.0/9.9 MB 3.4 MB/s eta 0:00:02
   --------------------------- ------------ 6.8/9.9 MB 3.4 MB/s eta 0:00:01
   ------------------------------ --------- 7.6/9.9 MB 3.4 MB/s eta 0:00:01
   -------------------------------- ------- 8.1/9.9 MB 3.4 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.9 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 3.4 MB/s  0:00:02
Downloading numpy-2.4.4-cp314-cp314-win_amd64.whl (12.4 MB)
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.4 MB 3.5 MB/s eta 0:00:04
   ---- ----------------------------------- 1.3/12.4 MB 3.5 MB/s eta 0:00:04
   ------ --------------------------------- 2.1/12.4 MB 3.5 MB/s eta 0:00:03
   -------- ------------------------------- 2.6/12.4 MB 3.5 MB/s eta 0:00:03
   ---------- ----------------------------- 3.4/12.4 MB 3.5 MB/s eta 0:00:03
   ------------- -------------------------- 4.2/12.4 MB 3.5 MB/s eta 0:00:03
   --------------- ------------------------ 4.7/12.4 MB 3.4 MB/s eta 0:00:03
   ----------------- ---------------------- 5.5/12.4 MB 3.4 MB/s eta 0:00:03
   -------------------- ------------------- 6.3/12.4 MB 3.4 MB/s eta 0:00:02
   --------------------- ------------------ 6.8/12.4 MB 3.4 MB/s eta 0:00:02
   ------------------------ --------------- 7.6/12.4 MB 3.4 MB/s eta 0:00:02
   -------------------------- ------------- 8.1/12.4 MB 3.3 MB/s eta 0:00:02
   ---------------------------- ----------- 8.9/12.4 MB 3.4 MB/s eta 0:00:02
   ------------------------------- -------- 9.7/12.4 MB 3.4 MB/s eta 0:00:01
   -------------------------------- ------- 10.2/12.4 MB 3.4 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.4 MB 3.4 MB/s eta 0:00:01
   ------------------------------------- -- 11.5/12.4 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.4 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 3.3 MB/s  0:00:03
Downloading tzdata-2026.1-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed numpy-2.4.4 pandas-3.0.2 tzdata-2026.1

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'C:\Users\jaana\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import pandas as pd
import duckdb

In [103]:
data = pd.DataFrame({
    "name": ["A","B","C"],
    "age": [30,25,35],
    "city": ["York", "Los", "Chi"]
})
data

  name  age  city
0    A   30  York
1    B   25   Los
2    C   35   Chi

In [106]:
data.to_csv("not_very_sensible_data.csv", index=False)

In [107]:
people = pd.read_csv("not_very_sensible_data.csv")
people

  name  age  city
0    A   30  York
1    B   25   Los
2    C   35   Chi

In [110]:
people[["name", "age"]]

  name  age
0    A   30
1    B   25
2    C   35

In [113]:
!pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\jaana\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from scikit-learn) (2.4.4)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.1 MB 4.0 MB/s eta 0:00:02
   ------ --------------------------------- 1.3/8.1 MB 3.6 MB/s eta 0:00:02
   ---------- ----------------------------- 2.1/8.1 MB 3.7 MB/s eta 0:00:02
   -------------- ------------------------- 2.9/8.1 MB 3.7 MB/s eta 0:00:02
   ------------------ --------------------- 3.7/8.1 MB 3.7 MB/s eta 0:00:02
   ---------------------- ----------------- 4.5/8.1 MB 3.7 MB/s eta 0:00:01
   ------------------------- -------------- 5.2/8.1 MB 3.7 MB/s eta 0:00:01
   ---------------------------- ----------- 5.8/8.1 MB 3.6 MB/s eta 0:00:01
   ------------------------------- -------- 6.3/8.1 MB 3.5 MB/s eta 0:00:01
   ------------------------------------ --- 7.3/8.1 MB 3.6 MB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 3.5 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 3.4 MB/s  0:00:02
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl (37.3 MB)
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
    --------------------------------------- 0.5/37.3 MB 3.1 MB/s eta 0:00:12
   - -------------------------------------- 1.3/37.3 MB 3.2 MB/s eta 0:00:12
   - -------------------------------------- 1.8/37.3 MB 3.1 MB/s eta 0:00:12
   -- ------------------------------------- 2.4/37.3 MB 3.1 MB/s eta 0:00:12
   --- ------------------------------------ 2.9/37.3 MB 3.0 MB/s eta 0:00:12
   --- ------------------------------------ 3.7/37.3 MB 3.0 MB/s eta 0:00:12
   ---- ----------------------------------- 4.5/37.3 MB 3.1 MB/s eta 0:00:11
   ----- ---------------------------------- 5.2/37.3 MB 3.2 MB/s eta 0:00:10
   ------ --------------------------------- 6.0/37.3 MB 3.3 MB/s eta 0:00:10
   ------- -------------------------------- 6.8/37.3 MB 3.4 MB/s eta 0:00:10
   -------- ------------------------------- 7.6/37.3 MB 3.4 MB/s eta 0:00:09
   -------- ------------------------------- 8.4/37.3 MB 3.4 MB/s eta 0:00:09
   --------- ------------------------------ 9.2/37.3 MB 3.4 MB/s eta 0:00:09
   ---------- ----------------------------- 10.0/37.3 MB 3.4 MB/s eta 0:00:08
   ----------- ---------------------------- 10.5/37.3 MB 3.4 MB/s eta 0:00:08
   ------------ --------------------------- 11.3/37.3 MB 3.4 MB/s eta 0:00:08
   ------------ --------------------------- 11.8/37.3 MB 3.3 MB/s eta 0:00:08
   ------------- -------------------------- 12.3/37.3 MB 3.3 MB/s eta 0:00:08
   ------------- -------------------------- 12.6/37.3 MB 3.2 MB/s eta 0:00:08
   -------------- ------------------------- 13.4/37.3 MB 3.2 MB/s eta 0:00:08
   -------------- ------------------------- 13.9/37.3 MB 3.2 MB/s eta 0:00:08
   --------------- ------------------------ 14.7/37.3 MB 3.2 MB/s eta 0:00:08
   ---------------- ----------------------- 14.9/37.3 MB 3.1 MB/s eta 0:00:08
   ---------------- ----------------------- 15.5/37.3 MB 3.1 MB/s eta 0:00:08
   ----------------- ---------------------- 16.0/37.3 MB 3.1 MB/s eta 0:00:07
   ----------------- ---------------------- 16.5/37.3 MB 3.1 MB/s eta 0:00:07
   ------------------ --------------------- 17.0/37.3 MB 3.1 MB/s eta 0:00:07
   ------------------ --------------------- 17.6/37.3 MB 3.0 MB/s eta 0:00:07
   ------------------- -------------------- 18.4/37.3 MB 3.0 MB/s eta 0:00:07
   -------------------- ------------------- 18.9/37.3 MB 3.0 MB/s eta 0:00:07
   --------------------- ------------------ 19.7/37.3 MB 3.1 MB/s eta 0:00:06
   --------------------- ------------------ 20.2/37.3 MB 3.1 MB/s eta 0:00:06
   ---------------------- ----------------- 21.0/37.3 MB 3.1 MB/s eta 0:00:06
   ----------------------- ---------------- 21.5/37.3 MB 3.1 MB/s eta 0:00:06
   ----------------------- ---------------- 22.0/37.3 MB 3.0 MB/s eta 0:00:06
   ------------------------ --------------- 22.5/37.3 MB 3.0 MB/s eta 0:00:05
   ------------------------- -------------- 23.3/37.3 MB 3.0 MB/s eta 0:00:05
   ------------------------- -------------- 24.1/37.3 MB 3.1 MB/s eta 0:00:05
   -------------------------- ------------- 25.2/37.3 MB 3.1 MB/s eta 0:00:04
   --------------------------- ------------ 26.0/37.3 MB 3.1 MB/s eta 0:00:04
   ---------------------------- ----------- 26.7/37.3 MB 3.1 MB/s eta 0:00:04
   ----------------------------- ---------- 27.8/37.3 MB 3.2 MB/s eta 0:00:03
   ------------------------------ --------- 28.6/37.3 MB 3.2 MB/s eta 0:00:03
   ------------------------------- -------- 29.4/37.3 MB 3.2 MB/s eta 0:00:03
   -------------------------------- ------- 30.1/37.3 MB 3.2 MB/s eta 0:00:03
   --------------------------------- ------ 30.9/37.3 MB 3.2 MB/s eta 0:00:02
   ---------------------------------- ----- 31.7/37.3 MB 3.3 MB/s eta 0:00:02
   ---------------------------------- ----- 32.5/37.3 MB 3.3 MB/s eta 0:00:02
   ----------------------------------- ---- 33.3/37.3 MB 3.3 MB/s eta 0:00:02
   ------------------------------------ --- 34.1/37.3 MB 3.3 MB/s eta 0:00:01
   ------------------------------------- -- 34.9/37.3 MB 3.3 MB/s eta 0:00:01
   -------------------------------------- - 35.7/37.3 MB 3.3 MB/s eta 0:00:01
   ---------------------------------------  36.4/37.3 MB 3.3 MB/s eta 0:00:01
   ---------------------------------------  37.2/37.3 MB 3.3 MB/s eta 0:00:01
   ---------------------------------------- 37.3/37.3 MB 3.3 MB/s  0:00:11
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn

   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ---------------------------------------- 4/4 [scikit-learn]

Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.1 threadpoolctl-3.6.0

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [111]:
!pip3 install duckdb

Collecting duckdb
  Downloading duckdb-1.5.1-cp314-cp314-win_amd64.whl.metadata (4.2 kB)
Downloading duckdb-1.5.1-cp314-cp314-win_amd64.whl (13.6 MB)
   ---------------------------------------- 0.0/13.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/13.6 MB 3.4 MB/s eta 0:00:04
   --- ------------------------------------ 1.3/13.6 MB 3.3 MB/s eta 0:00:04
   ----- ---------------------------------- 1.8/13.6 MB 3.2 MB/s eta 0:00:04
   ------- -------------------------------- 2.6/13.6 MB 3.2 MB/s eta 0:00:04
   ---------- ----------------------------- 3.4/13.6 MB 3.3 MB/s eta 0:00:04
   ----------- ---------------------------- 3.9/13.6 MB 3.3 MB/s eta 0:00:03
   ------------- -------------------------- 4.7/13.6 MB 3.3 MB/s eta 0:00:03
   --------------- ------------------------ 5.2/13.6 MB 3.3 MB/s eta 0:00:03
   ----------------- ---------------------- 6.0/13.6 MB 3.2 MB/s eta 0:00:03
   -------------------- ------------------- 6.8/13.6 MB 3.3 MB/s eta 0:00:03
   --------------------- ------------------ 7.3/13.6 MB 3.3 MB/s eta 0:00:02
   ----------------------- ---------------- 8.1/13.6 MB 3.3 MB/s eta 0:00:02
   -------------------------- ------------- 8.9/13.6 MB 3.3 MB/s eta 0:00:02
   --------------------------- ------------ 9.4/13.6 MB 3.3 MB/s eta 0:00:02
   ------------------------------ --------- 10.2/13.6 MB 3.3 MB/s eta 0:00:02
   -------------------------------- ------- 11.0/13.6 MB 3.3 MB/s eta 0:00:01
   --------------------------------- ------ 11.5/13.6 MB 3.3 MB/s eta 0:00:01
   ------------------------------------ --- 12.3/13.6 MB 3.3 MB/s eta 0:00:01
   -------------------------------------- - 13.1/13.6 MB 3.3 MB/s eta 0:00:01
   ---------------------------------------- 13.6/13.6 MB 3.3 MB/s  0:00:04
Installing collected packages: duckdb
Successfully installed duckdb-1.5.1

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [232]:
from sklearn.datasets import load_iris
import pandas as pd

iris_data = load_iris()
iris = pd.DataFrame(iris_data.data, columns=iris_data.feature_names)
iris['target'] = iris_data.target
iris ['species'] = iris['target'].map(dict(enumerate(iris_data.target_names)))
iris.pop('target')
iris = iris.rename(columns={
    "sepal length (cm)": "sepal_length",
    "sepal width (cm)": "sepal_width",
    "petal length (cm)": "petal_length",
    "petal width (cm)": "petal_width"
})
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [233]:
iris.to_csv("iris.csv", index=False)

In [ ]:
duckdb.sql("""
    SELECT 
           species,
           avg(petal_length) AS avg_petal_length
    FROM iris
    GROUP BY species
       ORDER BY avg_petal_length DESC
 """).df()

      species  avg_petal_length
0   virginica             5.552
1  versicolor             4.260
2      setosa             1.462

In [146]:
def funktsioon_enne_voi_parast_kristust(aasta: int) -> str:
    if aasta < 0:
        return f"{abs(aasta)} B.C."
    else:
        return f"{aasta} A.D."
    
funktsioon_enne_voi_parast_kristust(12)

'12 A.D.'

In [176]:
inimesed = ['Kati', 'Mati', 'Silver','Hannes']
numbrid = ['esimene', 'teine', 'kolmas', 'neljas']

jarjekorranumber = 0

for nimi in inimesed:
    jarjekord = numbrid[jarjekorranumber].capitalize()
    if len(nimi) > 4:
        print (f"{jarjekord} inimene kannab pikka nime {nimi}")
    else:
        print(f"{jarjekord} inimene kannab lühikest nime {nimi}")
    jarjekorranumber += 1

Esimene inimene kannab lühikest nime Kati
Teine inimene kannab lühikest nime Mati
Kolmas inimene kannab pikka nime Silver
Neljas inimene kannab pikka nime Hannes

- vaja leida kogu hind
- kui hind on üle 100, siis 20%
- kui hind on üle 50, siis 10%

184+80,1+

In [204]:
def get_price(hinnad):
    total = sum(hinnad)

    if total > 100:
        total *= 0.8
    elif total > 50:
        total *= 0.9

    return int(total)


hinnad = [120, 45, 89, 200, 33, 75, 150, 10, 99, 101]

print(get_price(hinnad))

737

In [230]:


def get_discount(price: int) -> float:
    if price > 100:
        return price * 0.8
    if price > 50:
        return price *0.9
    return price

def get_price(prices: list[int]) -> float:
    tulemus = 0
    for hind in prices:
       (allahindlusega_hind) = get_discount(hind)
       tulemus = tulemus + allahindlusega_hind
    return tulemus 

def get_price_short(price: list[int]) -> float:
    return sum([get_discount(hind) for hind in price])

def get_price_short(price: list[int]) -> float:
    print (sum([get_discount(hind) for hind in price]))

hinnad = [120, 45, 89, 200, 33, 75, 150, 10, 99, 101]
get_price(hinnad)

781.5

In [228]:
hinnad = [120, 45, 89, 200, 33, 75, 150, 10, 99, 101]
[round(get_discount(hind), 2) for hind in hinnad]

[96.0, 45, 80.1, 160.0, 33, 67.5, 120.0, 10, 89.1, 80.8]